name: flutter_toybox
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.3
  audio_video_progress_bar: ^0.9.0
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.9
  firebase_core: ^1.6.0
  freezed_annotation:
  get_it: ^7.2.0
  just_audio: ^0.9.19
  provider: ^6.0.0
  rxdart: ^0.27.3
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.1.10
  geolocator: ^9.0.1
  riverpod: ^1.0.3
  dio: ^4.0.6
  json_serializable: ^6.3.1



dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/markdowns/
    - .env.development

