// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD020YYb7C4Qm8Gmwhum6wjrSr8TF4-5Xw',
    appId: '1:464877474049:web:51c41ea08c9d3ea8788b00',
    messagingSenderId: '464877474049',
    projectId: 'flutter-toybox',
    authDomain: 'flutter-toybox.firebaseapp.com',
    storageBucket: 'flutter-toybox.appspot.com',
    measurementId: 'G-M39EVELLM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsnV3ECnqV4eGZWJ0ha87almQ8XdFNOYw',
    appId: '1:464877474049:android:ccc6a8d293ca8a27788b00',
    messagingSenderId: '464877474049',
    projectId: 'flutter-toybox',
    storageBucket: 'flutter-toybox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgM13fT7RZCDt5a_9xo5DWVSwwhqK1khc',
    appId: '1:464877474049:ios:d56a84a725ea165f788b00',
    messagingSenderId: '464877474049',
    projectId: 'flutter-toybox',
    storageBucket: 'flutter-toybox.appspot.com',
    androidClientId: '464877474049-nbipf68u8r4pcch41uuvs99eemik35ch.apps.googleusercontent.com',
    iosClientId: '464877474049-l7gn9c37qkiqq4e1cfobdgmi9nc7kbl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.SquareSample',
  );
}
